openapi: 3.0.0
info:
  version: 1.0.0
  title: Stask
servers:
  - url: 'http://localhost:3000'
paths:
    /api/user/project/:
    get:
      summary: 'Gets info about project with lane_info(lane_id),so as to fetch prefilled fields/maps'
      consumes:
        - application/json
      parameters:
        - name: id
          in: path
          description: 
          required: true
          schema:
            $ref: '#/componenet/schemas/Post' 
      responses:
        '200':
          description: 'Sample response: Details about a user by ID'
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
    /api/user/project/delete/{id}:
    delete:
      summary: 'Delete particular project'
      consumes:
        - application/json
      parameters:
        - name: id
          in: path
          description: 
          required: true
          schema:
            $ref: '#/componenet/schemas/Post' 
      responses:
        '200':
          description: 'Sample response: Details about a user by ID'
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    /api/user/project/add:
    post:
      summary: 'Add a new project'
      consumes:
        - application/json
      parameters:
        - name: id
          in: body
          description: 
          required: true
          schema:
            $ref: '#/componenet/schemas/Post' 
      responses:
        '200':
          description: 'Sample response: Details about a user by ID'
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        
    /api/user/project/edit:
    post:
      summary: 'Update a particular project'
      consumes:
        - application/json
      parameters:
        - name: id
          in: body
          description: 
          required: true
          schema:
            $ref: '#/componenet/schemas/Post' 
      responses:
        '200':
          description: 'Sample response: Details about a user by ID'
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
    /api/user/persona/{id}:
    get:
      summary: 'Get details of particular User'
      consumes:
        - application/json
      parameters:
        - name: id
          in: path
          description: 
          required: true
          schema:
            $ref: '#/componenet/schemas/User' 
      responses:
        '200':
          description: 'Sample response: Details about a user by ID'
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
    /api/user/persona/add:
    post:
      summary: 'Add User'
      consumes:
        - application/json
      parameters:
        - name: id
          in: body
          description: 
          required: true
          schema:
            $ref: '#/componenet/schemas/User' 
      responses:
        '200':
          description: 'Sample response: Details about a user by ID'
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
    /api/user/persona/edit/{id}:
    post:
      summary: 'Update particular User'
      consumes:
        - application/json
      parameters:
        - name: id
          in: body
          description: 
          required: true
          schema:
            $ref: '#/componenet/schemas/User' 
      responses:
        '200':
          description: 'Sample response: Details about a user by ID'
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
    /api/user/persona/addu:
    post:
      summary: 'Add user to particular project'
      consumes:
        - application/json
      parameters:
        - name: id
          in: body
          description: 
          required: true
          schema:
            $ref: '#/componenet/schemas/Post' 
      responses:
        '200':
          description: 'Sample response: Details about a user by ID'
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
    /api/user/lane/{id}:
    get:
      summary: 'Get all lanes of particular user project'
      consumes:
        - application/json
      parameters:
        - name: id
          in: path
          description: 
          required: true
          schema:
            $ref: '#/componenet/schemas/lane' 
      responses:
        '200':
          description: 'Sample response: Details about a user by ID'
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lane'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
    /api/user/lane/add:
    post:
      summary: 'add the lane to the current users(uid) project(pid), update the lane_id in Projects attr(DB)' 
      consumes:
        - application/json
      parameters:
        - name: id
          in: body
          description: 
          required: true
          schema:
            $ref: '#/componenet/schemas/lane' 
      responses:
        '200':
          description: 'Sample response: Details about a user by ID'
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lane'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    /api/user/lane/node/add:
    post:
      summary: 'add the node to the current users(uid) project(pid) particular node' 
      consumes:
        - application/json
      parameters:
        - name: id
          in: body
          description: 
          required: true
          schema:
            $ref: '#/componenet/schemas/lane' 
      responses:
        '200':
          description: 'Sample response: Details about a user by ID'
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lane'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
    
components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
        - email
        - password
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        password:
          type: string
    Post:
        type: object
        required:
          - id
          - title
          - description
        properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        contributors:
          type: object
    bmc:
        type: object
        required:
          - id
          - title
          - description
        properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        contributors:
          type: object
          
    lane:
        type: object
        required:
          - id
          - title
          - description
        properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        contributors:
          type: object
        pid:
          type: object
        node:
          type: object
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string